language: node_js
node_js:
- '0.11'
- '0.10'
sudo: false

cache:
  directories:
    - $HOME/.yarn
    - $HOME/.yarn-cache
    - $HOME/.cache # includes bowers cache
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - "phantomjs --version"

install:
  - "yarn global add bower"
  - "yarn install --prefer-offline"
  - "bower install"
